### ISSUE TITLE
Launcher unresponsive to close x

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_launcher#134]
Just noting my experience in Linux of the Launcher becoming unresponsive to close x. User Ctrl-C crashes out with error:
```
/home/davidpbrown/SAFE/safe_launcher-v0.4.3-linux-x64/resources/app.asar/api/ffi/worker.js:15
    if (!handler) {
         ^

ReferenceError: handler is not defined
    at process.cleanUp (/home/davidpbrown/SAFE/safe_launcher-v0.4.3-linux-x64/resources/app.asar/api/ffi/worker.js:15:10)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
```
Then new launcher reports:
```
Unable to start Server. Port 8101 already in use.
```
Solution used was to force a hard kill via
> ps aux | grep 'launcher'

suggesting the process to kill.

**Comment by davidpbrown** [comment]
This occurred again when the Demo app was closed, before the first instance of Launcher authorising it had completed. Launcher then would not close via GUI.

Once forced to close, starting another instance of the Launcher, gave an error about the port being unavailable, so evidently the stopping of it was messy.

snapshots at https://imgur.com/a/TLGiR

Expected: Launcher should always respond to request to close[x], it's showing as entirely busy while authorising the app perhaps isn't ideal.
